#!/bin/bash

cd $QIE10ROOT/src && python $QIE10ROOT/src/makeEMAP.py -c $1 && rm $QIE10ROOT/cfg/ngHF_emap.txt && mv $QIE10ROOT/src/ngHF_emap.txt $QIE10ROOT/cfg/ngHF_emap.txt && python $QIE10ROOT/src/ActivateChannels.py && cd - >/dev/null
